---
- hosts: 127.0.0.1
  connection: local
  become: true
  vars:
    created_username: "{{ lookup('ansible.builtin.env', 'USER') }}"

  tasks:

    - name: Setup passwordless sudo
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%sudo'
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'
        validate: '/usr/sbin/visudo -cf %s'

    - name: Create a new regular user with sudo privileges
      user:
        name: "{{ created_username }}"
        state: present
        groups: sudo
        append: true
        create_home: true

    - name: creates ansible.cfg from default
      ansible.builtin.copy:
        src: ansible.cfg.default
        dest: /etc/ansible/ansible.cfg
        owner: root
        group: root
        mode: "0644"
        backup: true    
    